### PR TITLE
Added SOLID entry

### PR DESCRIPTION
**Pull request by gordoncavanaugh**
@jchartrand The file looks correct in my fork.  How has the formatting changed?

### CODE REVIEW

**Comment by jchartrand** [comment]
@gordoncavanaugh 

You can see the difference between your commit and the prior commit here:

https://github.com/digitalcredentials/sandbox-registry/pull/4/commits/f878215960f3da9f8f187db22760cf817f0b887d

Ideally we want the green + bits to only show your new addition. As it is, it shows the removal (the red - bits) of most of the file, and then the addition of what is probably the same stuff, but it isn't easy to tell that. We want it so that later if someone is looking through the commits, it only takes a quick glance to see what was changed.

I can see that your commit has at least removed some spaces.  So nothing that would change the semantics of the json, but it does mess up the diff a bit.

**Comment by gordoncavanaugh** [comment]
@jchartrand I'm guessing my editor changed the line endings.  I'll see if I can figure out a way to correct this.

**Comment by gordoncavanaugh** [comment]
@jchartrand I updated the registry.json file in my original fork by copying and pasting the registry.jon file from the main branch, and adding our entry.  I committed the changes, but I cannot seem to create another pull request.  Github doesn't show any changes between my fork and main. 

I was not able to create another fork.  Do I have to delete the existing one first?  Thanks.

**Comment by jchartrand** [comment]
@gordoncavanaugh 

When you create a PR, you create it for a branch, which in this case is your 'main' branch.  And if you make commits to that branch after submitting it as a PR, the new commits also become part of the PR, which is what has happened in this case:  your second commit has become part of the PR.

But, the second commit still seems to have reformatted the json.

Yes, you are correct: a GitHub account can only have one forked copy of a project. So, yes, you'd have to delete your fork, and fork it again if you want to start from scratch. Which is easily done, though, and would then let you edit the existing registry.json file directly from the GitHub web page, which hopefully wouldn't change the formatting.

Alternatively, if you'd rather not fiddle with it anymore, I can commit your new did myself.

**Pull request closed without merging**
